"""Auto-generated migration

Revision ID: 13604f702d6a
Revises: 5ba03af580e8
Create Date: 2025-06-26 09:23:27.056446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13604f702d6a'
down_revision = '5ba03af580e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create the enum type first
    interview_language_enum = sa.Enum('HEBREW', 'ENGLISH', 'ARABIC', name='interviewlanguage')
    interview_language_enum.create(op.get_bind())

    # Add the column with a default value for existing records
    op.add_column('interviews', sa.Column('language', interview_language_enum, nullable=False, server_default='HEBREW'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'language')
    # Drop the enum type
    sa.Enum(name='interviewlanguage').drop(op.get_bind())
    # ### end Alembic commands ###
