"""Auto-generated migration

Revision ID: 1c2fc592ce87
Revises: e80616ea0214
Create Date: 2025-06-25 18:12:42.662410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c2fc592ce87'
down_revision = 'e80616ea0214'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('candidate_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('risk_factors', sa.JSON(), nullable=False),
    sa.Column('overall_risk_level', sa.String(), nullable=False),
    sa.Column('general_observation', sa.Text(), nullable=False),
    sa.Column('final_grade', sa.String(), nullable=False),
    sa.Column('general_impression', sa.Text(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('key_strengths', sa.JSON(), nullable=False),
    sa.Column('areas_of_concern', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['candidates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('candidate_id')
    )
    op.create_index(op.f('ix_candidate_reports_id'), 'candidate_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candidate_reports_id'), table_name='candidate_reports')
    op.drop_table('candidate_reports')
    # ### end Alembic commands ###
