"""Auto-generated migration

Revision ID: 2a754b0ba1b9
Revises: 3570eb3467e3
Create Date: 2025-06-24 12:45:24.392354

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a754b0ba1b9'
down_revision = '3570eb3467e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidates', sa.Column('created_by_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'candidates', 'users', ['created_by_user_id'], ['id'])
    op.add_column('interviews', sa.Column('created_by_user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'interviews', 'users', ['created_by_user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'interviews', type_='foreignkey')
    op.drop_column('interviews', 'created_by_user_id')
    op.drop_constraint(None, 'candidates', type_='foreignkey')
    op.drop_column('candidates', 'created_by_user_id')
    # ### end Alembic commands ###
