"""Auto-generated migration

Revision ID: 31917c56d930
Revises: 16207521eda5
Create Date: 2025-06-26 12:30:48.936400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31917c56d930'
down_revision = '16207521eda5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interview_sessions', sa.Column('current_question_index', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interview_sessions', 'current_question_index')
    # ### end Alembic commands ###
