"""Auto-generated migration

Revision ID: 31920b96acad
Revises: 1c2fc592ce87
Create Date: 2025-06-25 20:09:42.055361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31920b96acad'
down_revision = '1c2fc592ce87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_prompts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prompt_type', sa.Enum('SMALL_LLM', 'JUDGE', 'GUARDRAILS', name='prompttype'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_custom_prompts_id'), 'custom_prompts', ['id'], unique=False)
    op.create_index(op.f('ix_custom_prompts_prompt_type'), 'custom_prompts', ['prompt_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_custom_prompts_prompt_type'), table_name='custom_prompts')
    op.drop_index(op.f('ix_custom_prompts_id'), table_name='custom_prompts')
    op.drop_table('custom_prompts')
    # ### end Alembic commands ###
