"""Auto-generated migration

Revision ID: 5ba03af580e8
Revises: 31920b96acad
Create Date: 2025-06-25 20:15:59.110113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba03af580e8'
down_revision = '31920b96acad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
