"""Auto-generated migration

Revision ID: b96d00b294e2
Revises: b317e7e85f1e
Create Date: 2025-07-01 13:09:47.452835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b96d00b294e2'
down_revision = 'b317e7e85f1e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('interviews', sa.Column('initial_greeting', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('interviews', 'initial_greeting')
    # ### end Alembic commands ###
